# Refresh tmux config with r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

unbind C-b              # Unbind the default prefix key
set -g prefix C-Space   # Set new prefix key to Ctrl+Space
set -g mouse on         # Enable mouse support
set -g set-clipboard on # Use system clipboard

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-show-empty-plugins false
set -g @dracula-plugins "battery ram-usage time"
#set -g @dracula-transparent-powerline-bg true
#set -g status-position top
#set -g @dracula-show-edge-icons true

run '~/.config/tmux/plugins/tpm/tpm'
